[project]
name = "lite-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.10.7",
    "gymnasium[classic-control]>=1.2.0",
    "tfp-nightly[jax]>=0.26.0.dev20250709",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
cpu = [
    "jax>=0.6.2",
]
dev = [
    "jaxtyping>=0.3.2",
    "matplotlib>=3.10.3",
    "pyqt6>=6.9.1",
    "pytest>=8.4.1",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
]
